name: Build and publish docker image for each commit in the officiala nanocurrency/nano-node repo
#on: [push, pull_request]
on:
  schedule:
    - cron: '0/5 * * * *'  # "every 30 minutes

jobs:
  publish_docker_image_on_new_commit:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout gr0vity-dev/nano-node-builder          
        uses: actions/checkout@v3
      - name: Compare commit hash between source and mirror
        id: compare_hash
        run: |
          LATEST_COMMIT_BUILDER=$(cat ./docker_builds/latest_hash.txt)
          LATEST_COMMIT_SOURCE=$(curl -s --location --request GET 'https://api.github.com/repos/nanocurrency/nano-node/commits/develop' | jq -r '.sha')
          if [ "$LATEST_COMMIT_SOURCE" == "" ];then
            #github api request failed 
            exit 0
          fi
          if [ "$LATEST_COMMIT_BUILDER" != "$LATEST_COMMIT_SOURCE" ]; then            
            echo "continue=1" >> $GITHUB_OUTPUT
            echo "LATEST_COMMIT_SOURCE=$LATEST_COMMIT_SOURCE" >> $GITHUB_OUTPUT
            
            #Update nano-node-builder
            echo $LATEST_COMMIT_SOURCE > ./docker_builds/latest_hash.txt
            echo $(date +%s):$LATEST_COMMIT_SOURCE >> ./docker_builds/all_builds.txt
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git add .
            git commit -m "update docker builds"
            git push origin main
          fi   
      - name: checkout nanocurrency/nano-node
        if: ${{ steps.compare_hash.outputs.continue > 0 }}
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
        with:
          repository: nanocurrency/nano-node
          submodules: "recursive"
          ref: develop
      - name: build docker image
        if: ${{ steps.compare_hash.outputs.continue > 0 }}
        run: |
          DOCKER_TAG=${{ steps.compare_hash.outputs.LATEST_COMMIT_SOURCE }}
          docker build -f docker/node/Dockerfile -t gr0v1ty/nano-node .
          # LOGIN to dockerhub
          echo ${{ secrets.DH_PWD }} | docker login -u gr0v1ty --password-stdin
          docker tag gr0v1ty/nano-node gr0v1ty/nano-node:$DOCKER_TAG          
          # Push as latest
          docker push gr0v1ty/nano-node
          docker push gr0v1ty/nano-node:latest
          # Push with commit hash as version
          docker push gr0v1ty/nano-node:$DOCKER_TAG
      
